import Head from 'next/head'
import Link from 'next/link'
import Avatar from 'components/Avatar'
import Button from 'components/Button'
import GitHub from 'components/Icons/GitHub'
import styles from 'styles/Start.module.css'
import { loginWithGitHub, onAuthStateChanged } from '../firebase/client'
import { useEffect, useState } from 'react'

export default function Home() {
  const [user, setUser] = useState(undefined)

  useEffect(() => {
    onAuthStateChanged(setUser)
  }, [])

  const handleClick = () => {
    loginWithGitHub().then(user => {
      console.log(user)
      setUser(user)
    }).catch(err => {
      console.log(err)
    })
  }

  return (
    <div>
      <Head>
        <title>Devtter</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles.startDiv}>
        <Link href="/"><img src='/remlogo.png' alt='Logo' className={styles.logo} /></Link>
        <h1 className={styles.title}>Devtter</h1>
        <h2 className={styles.subtitle}>Talk about development with developers!</h2>
        <span className={styles.buttons}>
            {
              user === null && 
              <Button onClick={handleClick}>
                <GitHub fill='#fff' width={24} height={24} />
                Login with GitHub
              </Button>
            }
            {
              user && user.avatar &&
              <span>
                <Avatar alt={user.userName} src={user.avatar} text={user.userName} />
              </span>
            }
        </span>
      </div>
    </div>
  )
}
