import Head from 'next/head'
import Link from 'next/link'
import Button from '../components/Button'
import GitHub from '../components/Icons/GitHub'
import styles from '../styles/Home.module.css'
import { loginWithGitHub } from '../firebase/client'
import { useState } from 'react'

export default function Home() {
  const [user, setUser] = useState(null)
  const handleClick = () => {
    loginWithGitHub().then(user => {
      const {avatar, username} = user
      setUser(user)
    }).catch(err => {
      console.log(err)
    })
  }

  return (
    <div>
      <Head>
        <title>Devtter</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <section className={styles.homeSection}>
        <Link href="/"><img src='/remlogo.png' alt='Logo' className={styles.logo} /></Link>
        <h1 className={styles.title}>Devtter</h1>
        <h2 className={styles.subtitle}>Talk about development with developers!</h2>
        <span className={styles.buttons}>
          <Button onClick={handleClick}>
            <GitHub fill='#fff' width={24} height={24} />
            Login with GitHub
          </Button>
        </span>
      </section>
    </div>
  )
}
